# Generated by Django 4.1.5 on 2023-02-05 20:35

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.TextField(max_length=100)),
                ('privacy_status', models.IntegerField(choices=[(1, 'Private'), (2, 'Public'), (3, 'Secret')], default=1)),
                ('description', models.TextField(max_length=500)),
                ('localization', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('start_time', models.DateTimeField()),
                ('stop_time', models.DateTimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_parties', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(related_name='parties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
