# Generated by Django 4.1.6 on 2023-02-09 22:29

import LiquorLovers.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0002_alter_party_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='image',
            field=models.ImageField(default='defaults/parties/default.png', upload_to=LiquorLovers.utils.uuid_upload_to),
        ),
    ]
