# Generated by Django 4.1.7 on 2023-03-16 20:07

import LiquorLovers.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0005_alter_party_image_partyrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='party',
            old_name='localization',
            new_name='location',
        ),
        migrations.AlterField(
            model_name='party',
            name='image',
            field=models.ImageField(default='defaults/parties/default.png', upload_to=LiquorLovers.utils.uuid_upload_to),
        ),
    ]
